#!/bin/bash

if [[ "$(synclient -l | grep TouchpadOff | sed 's/.*= //')" == "1" ]]; then
	echo "Turning Touchpad On"
	synclient TouchpadOff=0
else
	echo "Turning Touchpad Off"
	synclient TouchpadOff=1
fi
